### PR TITLE
Feat etape2 partie6

### PR DESCRIPTION
**Pull request by armandooj**
Now we don't have to explicitly call Halt(), we can just return 0 to exit programs.

### CODE REVIEW

**Comment by thanhluan001** [comment]
Why in PutChar.c you put return 33; instead of return 0?

**Comment by armandooj** [comment]
@thanhluan001 my bad, I was testing it. We don't using right now but the assignment asked how we would retrieve the return value.

**Comment by thanhluan001** [comment]
Great. Let me eat and then I will try it out on my computer to make sure it's compiled. Then we can close this pull request :dancers:

**Comment by thanhluan001** [comment]
Could you check. It doesn't work when I do ./nachos-step2 ./putchar

The same goes to halt and other function.

**Comment by thanhluan001** [comment]
It works perfectly. I'll merge it to master :D

**Pull request merged**
