### PR TITLE
Virtual Memory

### PR DESCRIPTION
**Pull request by armandooj**

### CODE REVIEW

**Comment by thanhluan001** [comment]
Why you need pid and tid? They are just ID. Using tid for stack have the same problem with sychonization as Vania said. If a thread is dead and some new thread come then they would have the same tid and I'd wait for the wrong thread.

**Comment by thanhluan001** [comment]
Why my shit moving around? Why JoinWaiting is on thread.cc? It doesn't make any sense,

**Comment by thanhluan001** [comment]
@armandooj  Why threadcount is on machine.cc? It makes sense inside a process only.

**Comment by thanhluan001** [comment]
This branch is horrible. Delete it. Why you have time to do all this "cosmetics" commits? Now what I have is code with beautiful indentation and horrible logic.

**Comment by armandooj** [comment]
Pid and tid are always unique, I need them for the synch. They have nothing to do with the stack.. I have a "stackLocation" variable used for that. If a thread days what you are saying never will happen. 

do_UserThreadJoin is where you had id, what do you mean? (it's in userthread.cc). I thought you wanted it to be there, it can be anywhere.. but for now its fine because that way it's always unique.

Delete it if you want but take my stuff. I indent because it takes one command and otherwise its impossible to read the code

**Pull request merged**
